services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-WEBAUTH-USER
      - GF_AUTH_PROXY_HEADER_PROPERTY=username
      - GF_AUTH_PROXY_HEADERS=Name:X-WEBAUTH-NAME Email:X-WEBAUTH-EMAIL
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
      - GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN=false
      - GF_SERVER_ROOT_URL=${ROOT_URL:-http://localhost:3200}
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_AUTH_PROXY_SYNC_TTL=60
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_LOG_LEVEL=info
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - grafana

  auth:
    build: ./auth
    depends_on:
      - grafana
    environment:
      - B2C_TENANT_NAME=${B2C_TENANT_NAME}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - SIGNUPSIGNIN_USER_FLOW=${SIGNUPSIGNIN_USER_FLOW}
      - GRAFANA_URL=http://grafana:3000
      - ROOT_URL=${ROOT_URL:-http://localhost:3200}
    networks:
      - grafana

  nginx:
    build: 
      context: ./nginx
      args:
        - DEPLOYMENT=${DEPLOYMENT:-local}
    ports:
      - "${NGINX_PORT:-3200}:${NGINX_PORT:-3200}"
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    depends_on:
      - auth
      - grafana
    environment:
      - ROOT_URL=${ROOT_URL:-http://localhost:3200}
      - NGINX_PORT=${NGINX_PORT:-3200}
      - SERVER_NAME=${SERVER_NAME:-localhost}
    networks:
      - grafana

volumes:
  grafana-storage:

networks:
  grafana:
    driver: bridge