services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-WEBAUTH-USER
      - GF_AUTH_PROXY_HEADER_PROPERTY=username
      - GF_AUTH_PROXY_HEADERS=Name:X-WEBAUTH-NAME Email:X-WEBAUTH-EMAIL
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
      - GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_AUTH_PROXY_SYNC_TTL=60
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_LOG_LEVEL=info
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - grafana

  auth:
    build: ./auth
    depends_on:
      - grafana    
    ports:
      - "5005:5005"
    environment:
      - AZURE_TENANT=${AZURE_TENANT}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_POLICY_NAME=${AZURE_POLICY_NAME}
      - GRAFANA_URL=http://grafana:3000
      - SSL_VERIFY=False
    networks:
      - grafana

volumes:
  grafana-storage:

networks:
  grafana:
    driver: bridge